### ISSUE TITLE
Bootstrap/serotonin i13 pro 16,6

### ISSUE THREAD

**Issue by lanigc** [c22dev/Geranium#24] opened 2024-03-20 02:14 UTC
Can I stop some demons that I don't need, I tried but it doesn't work, Inside the application they show that they are stopped, but in cocoatop they are still active

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.accessibility.axAuditDaemon.deviceservice</key>
	<false/>
	<key>com.apple.awdd</key>
	<true/>
	<key>com.apple.bootpd</key>
	<true/>
	<key>com.apple.coreduetd</key>
	<true/>
	<key>com.apple.coreidvd</key>
	<true/>
	<key>com.apple.dhcp6d</key>
	<true/>
	<key>com.apple.ftp-proxy-embedded</key>
	<false/>
	<key>com.apple.instruments.deviceservice</key>
	<false/>
	<key>com.apple.magicswitchd.companion</key>
	<true/>
	<key>com.apple.mobile.heartbeat</key>
	<true/>
	<key>com.apple.newsd</key>
	<true/>
	<key>com.apple.relevanced</key>
	<true/>
	<key>com.apple.security.otpaird</key>
	<true/>
	<key>com.apple.sosd</key>
	<true/>
	<key>com.apple.sysmond</key>
	<false/>
	<key>com.apple.tipsd</key>
	<true/>
	<key>com.apple.videosubscriptionsd</key>
	<true/>
	<key>com.openssh.sshd</key>
	<false/>
	<key>com.tigisoftware.filza.helper</key>
	<false/>
	<key>com.tigisoftware.filza.webdavserver</key>
	<false/>
	<key>org.hacx.hacxdaemon</key>
	<true/>
</dict>
</plist>

**Comment by lanigc** [comment] 2024-03-20 02:15
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.accessibility.axAuditDaemon.deviceservice</key>
	<false/>
	<key>com.apple.awdd</key>
	<true/>
	<key>com.apple.bootpd</key>
	<true/>
	<key>com.apple.coreduetd</key>
	<true/>
	<key>com.apple.coreidvd</key>
	<true/>
	<key>com.apple.dhcp6d</key>
	<true/>
	<key>com.apple.ftp-proxy-embedded</key>
	<false/>
	<key>com.apple.instruments.deviceservice</key>
	<false/>
	<key>com.apple.magicswitchd.companion</key>
	<true/>
	<key>com.apple.mobile.heartbeat</key>
	<true/>
	<key>com.apple.newsd</key>
	<true/>
	<key>com.apple.relevanced</key>
	<true/>
	<key>com.apple.security.otpaird</key>
	<true/>
	<key>com.apple.sosd</key>
	<true/>
	<key>com.apple.sysmond</key>
	<false/>
	<key>com.apple.tipsd</key>
	<true/>
	<key>com.apple.videosubscriptionsd</key>
	<true/>
	<key>com.openssh.sshd</key>
	<false/>
	<key>com.tigisoftware.filza.helper</key>
	<false/>
	<key>com.tigisoftware.filza.webdavserver</key>
	<false/>
	<key>org.hacx.hacxdaemon</key>
	<true/>
</dict>
</plist>

**Comment by 1ahmadbassam** [comment] 2024-03-20 08:16
What’s hacxdaemon? Which version of Bootstrap/Serotonin are you using?

**Comment by lanigc** [comment] 2024-03-20 11:12
BootStrap 1.2.1
Serotonin 1.2.1

Hack demon
https://www.ios-repo-updates.com/share/hacx-repository/

**Comment by 1ahmadbassam** [comment] 2024-03-20 11:48
How did you get the daemons working with Bootstrap? I can't reproduce it.

**Comment by c22dev** [comment] 2024-03-20 22:04
Hi y'all,
First of all, I won't and will never confirm nor tell you directly any daemon you might want to disable.
Secondly, regarding your issue, this is a duplicate of #23 and seem to only affect specific users. Could you specify your device/version combination? 
I'll close this issue once you reply, and I'd be very pleased if you could move discussion to the other issue afterwards.

**Closed** 2024-03-20 22:05 UTC

**Comment by lanigc** [comment] 2024-03-21 02:09
i fixt it thanks

**Comment by lanigc** [comment] 2024-03-24 18:07
I didn't know, but with version 1.1.1 it works

**Comment by c22dev** [comment] 2024-03-25 13:37
Yeah I understood.
The issue is that I haven't changed anything...
