### ISSUE TITLE
Have a scan for caches button in Cleaner tab

### ISSUE THREAD

**Issue by Void48** [c22dev/Geranium#12] opened 2024-02-07 11:41 UTC
Please don't automatically scan for caches, or at least make it optional when the app is first launched on the setup screen 👍

**Comment by c22dev** [comment] 2024-02-07 11:45
Okay
Fixed 
Will be released next release and pushed this afternoon

**Comment by c22dev** [comment] 2024-02-07 11:59
Oh I didn’t expected that one ! 
yeah ill try to fix it !! Sorry for the issue

**Closed** 2024-02-08 14:31 UTC
Labels: enhancement

**Comment by c22dev** [comment] 2024-02-22 15:29
The release is planned for today.

**Comment by c22dev** [comment] 2024-02-22 16:57
1.1.2 is out and should provide a fix for every of the issues/suggestions you mentioned !

**Comment by c22dev** [comment] 2024-02-22 17:48
> Thanks! I was partly hoping you’d be able to figure out how to make the resizing of the Maps animation smooth instead of just removing it, as I quite liked it (it was just laggy), but I’ll take it as it is now. 🫡

I definitely could have... so sorry for this. Will see if I can improve it, but the issue is that on my device and on the simulator it doesn't lag and is smooth...
